### ISSUE TITLE
Incorrect hashes in latest Panda update

### ISSUE THREAD

**Issue by RenierZA** [48klocs/dim-wish-list-sources#119]
I have found a few example where the hashes are for different weapon perks than intended.

Some I found, there might be more (just showing the first line for brevity)

```
// Tripwire Canary
dimwishlist:item=3849444474&perks=839105230,3142289711,247725512,1015611457

// Cold Front
dimwishlist:item=2814093983&perks=3250034553,3142289711,1428297954,2846385770

// Aurvandil FR6
dimwishlist:item=963710795&perks=839105230,3230963543,247725512,124408337

// Avalanche
dimwishlist:item=495940989&perks=839105230,1087426260,3300816228,2939589096
```

PS. The last one seems to be for `Enhanced Target Lock`, but the weapon is not craftable.

**Comment by 48klocs** [comment]
My tooling to find + clean up bogus rolls stopped working, so I didn't dig too far in to that all.

Thanks for the eye. I'll eventually get in and root around to see what's going on.

**Comment by 48klocs** [comment]
Tripwire Canary - an impossible build is called for. Logged that at https://www.reddit.com/r/sharditkeepit/comments/zokq3i/season_19_seraph_weapons_and_ikelos_weapons/j3dgybt/

Cold Front - a mix-up on curated vs. non-curated perk picks happened again. Logged that at https://www.reddit.com/r/sharditkeepit/comments/zl9s10/rngeez_dawning_breakdown/j3di79y/

Ditto Aurauruarualrdil (the name is confounding me) - https://www.reddit.com/r/sharditkeepit/comments/zokp78/season_19_world_drops/j3dj0bg/

Ditto Avalanche (the PvE roll) - https://www.reddit.com/r/sharditkeepit/comments/zl9s10/rngeez_dawning_breakdown/j3djpmp/
