### ISSUE TITLE
Season 20 + Lightfall Rolls

### ISSUE THREAD

**Issue by rileysea** [48klocs/dim-wish-list-sources#126]
Hello,

I wanted to know when the wishlist will be updated for Season 20 (Defiance) and the Lightfall expansion.

I am currently not trashing some of my new rolls since I'm not sure what's deemed worthy or ass.

**Comment by liminalAce** [comment]
As soon as: evaluators have time to get rolls, time to test them, and time to write up their opinions of those tests. Then, someone has the time to take all those write ups and convert them into hundreds of lines of wishlist items. 

There is never a set date. It is nearly never within 2 weeks. It gets done when it gets done. Wishlists are easier than ever to make if you need one now, get on it! 😀

**Comment by 48klocs** [comment]
Aye - I generally don't know until the folks making lists have them together, and I don't bug them for picks.

**Comment by rileysea** [comment]
> Aye - I generally don't know until the folks making lists have them together, and I don't bug them for picks.

Fair enough. As someone who's fairly new to these wishlists, I was curious if there was a timeline. Thanks for the input.

**Comment by 48klocs** [comment]
https://github.com/DestinyItemManager/DIM/wiki/FAQ#when-will-the-default-wish-list-be-updated-with-new-rolls
