### ISSUE TITLE
It would be helpful if more notes were to include Currator where a note is missing

### ISSUE THREAD

**Issue by TimMcJilton** [48klocs/dim-wish-list-sources#13]
```
$ grep -L -i notes * | grep .txt                          ~/code/dim-wish-list-sources
mercules_black_armory_and_sotp_rolls.txt
mercules_black_armory_pulse_bow.txt
mercules_crown_of_sorrow.txt
mercules_dreaming_city_breakdown_rolls.txt
mercules_erentil_and_opulence_iron_banner.txt
mercules_gambit_rolls.txt
mercules_iron_banner_bonus.txt
mercules_iron_banner.txt
mercules_last_wish_rolls.txt
mercules_menagerie.txt
panda_black_armory_picks.txt
panda_black_armory_pve_picks.txt
panda_black_armory_pvp_picks.txt
panda_forsaken_pve_rolls.txt
panda_forsaken_pvp_rolls.txt
panda_missing_black_armory_pve.txt
panda_missing_black_armory_pvp.txt
panda_penumbra_pve.txt
panda_penumbra_pvp.txt
panda_season_drifter_pve.txt
panda_season_drifter_pvp.txt
```
Around 21 files are missing any notes at all. I would propose we add the Currator + whether they marked it as PvE or PvP and if they intend it for console vs M&K.

Example being from `panda_black_armory_picks.txt` 
I would propose:
```
  3 //dead man walking (pvp pc)
  2 //notes: PandaPaxxy's PC PvP pick
  1 dimwishlist:item=3751622019&perks=445755710,3142289711,1168162263,2846385770
  0 dimwishlist:item=3751622019&perks=445755711,3142289711,1168162263,2846385770
  1 dimwishlist:item=3751622019&perks=445755704,3142289711,1168162263,2846385770
  2 dimwishlist:item=3751622019&perks=445755710,3177308360,1168162263,2846385770
```

I can help and throw up a PR for it. But don't want to go through it all if it is unwanted. This would help give silly new light players(like myself) an easier way to know why a gun was wishlisted or be able to find the source from DIM, or to be able to see which wishlist guns are PvP//PvE.

Possible notes added would be (for Panda as an example):
```
//notes: PandaPaxxy's pick
//notes: PandaPaxxy's PvE pick
//notes: PandaPaxxy's PvE PC pick
//notes: PandaPaxxy's PvE Console pick
//notes: PandaPaxxy's PvP pick
//notes: PandaPaxxy's PvP PC pick
//notes: PandaPaxxy's PvP Console pick
```

**Comment by 48klocs** [comment]
The first of those notes (simply saying it's from panda) is kind of value-free, so I have no interest in that.

The rest of them, where you're adding notes on mode / platform I'd be happy to get a PR for (but I also have no plan to go back and hunt them down myself), with the caveat that I'd want to see notes added to both source and voltron files.

**Comment by TimMcJilton** [comment]
@48klocs My plan was to only take what is currently a comment, and just convert it to a Note. I don't want to add what I believe Panda added it for, unless it's in the file name. Example being in  `panda_penumbra_pve.txt` all of those items should have `//notes: PandaPaxxy's PvE pick`

My hope was to do 1 PR to add them to the source files, and then the next time you update the Voltron the changes would be put into affect.  If you want me to update the Voltron file I can if you give me the ordering of files in order of more important to least important. (Overrides). I know the trash list goes last, but I don't know the order of the rest. 

When I search for grep -iE "(mercules|panda)" | grep -v notes | grep -v dimwishlist I get a mixture of 25 titles and comments. That helps me place 25 of the 39 files, but 14 I wouldn't know where it would go in the ordering. (I promise I'm not trying to be a pita here, I just want to make sure when I recreate the voltron file with comments I am doing it in the curated order you preferred) I'm guessing it is different because along the maintenance of voltron over time the style of moving something into voltron has changed and Dim  started Supporting more things.

**Comment by TimMcJilton** [comment]
Related PR 48klocs/dim-wish-list-sources#3 Probably will do what was suggested there of this for files that are specifically PvE vs PvP (unless M&Kb vs Console was mentioned) : 
```
//TopOfFileWithAllOfTheTitleAndBonusInfo
 //notes: PandaPaxxy's PvP pick

  //dead man walking (pvp pc)
 //notes: PandaPaxxy's PC PvP pick
  dimwishlist:item=3751622019&perks=445755710,3142289711,1168162263,2846385770
  dimwishlist:item=3751622019&perks=445755711,3142289711,1168162263,2846385770
 //notes: PandaPaxxy's PvP pick

 dimwishlist:item=3751622019&perks=445755704,3142289711,1168162263,2846385770
 dimwishlist:item=3751622019&perks=445755710,3177308360,1168162263,2846385770
//notes: 
```
So similar to what was mentioned I'm going to close the block with resetting it to empty EOF, and setting it back to the file primary note in any overrides. In generic files like lastWish I'll need to open and close like I do files anywhere PvE vs PvP is mentioned.

**Comment by 48klocs** [comment]
https://github.com/DestinyItemManager/DIM/blob/master/docs/COMMUNITY_CURATIONS.md#block-notes explains how block notes work - you can create a note line, which will apply, until a blank line is encountered, at which point the note block is treated as closed.

**Comment by TimMcJilton** [comment]
Opened up first PR. I don't know if I feel confident updating voltron without knowing the order in there. I will do a rough pass adding 
`/notes:PvE Pick` (or `PvE Console Pick` when specified). If that looks good I will open 2 more, one fore mercules missing comments, and then one with Voltron.

**Comment by TimMcJilton** [comment]
Threw in #16  for Voltron. Will go back to Mercules after I know you are okay with #15

**Comment by TimMcJilton** [comment]
I will say, there is a bit of an annoying weirdness with voltron and notes.  Because notes//Wishlist is found Top to bottom, Wendigo is both PvE and PvP picks from paxxy. So if we ever re-make Voltron from scratch and want to have accurate notes we'd need to discover the item is both listed in PvE and PvP and Add a note saying it is for both. 

Totally unrelated to this change, but something to consider in case I ever convince you to let me write a script to auto-gen Voltron from the source files.

**Comment by TimMcJilton** [comment]
Did it across mercules in #17 and made the awk script more .. of a script. Ran it against mercules (while changing the strings to include `Mercules - `.

It wouldn't take much to run that script across any lacking notes to add the curator of like `Mercules' Curated Pick` or `PandaPaxxy's Curated Pick` almost free. 

The other thing, How confident about Voltron containing all of the other source files in a good standing? are you sure you don't want(me) to modify Voltron to be an autogeneratable  file that compiles itself based on the Order in specified in an ordering file?

**Comment by 48klocs** [comment]
I'm... sort of confident?

I cut 'n pasted it together and have done some search and replaces. I've thought about scripting its generation, but I end up just playing games instead of doing that after I cut 'n paste more together.

**Comment by TimMcJilton** [comment]
Going to go ahead and close this issue since it is now complete. I'll open an issue about possibly making a script. It's pretty straight forward for me to make one. (Take less than 20 minutes to get a quick python script for this)

If you give me an order of the files like which ones should be first vs last I'll hook up a script for ya. Pretty much would add a file called `orderedFiles.json` that I'll read in, then loop through the files and poop out a voltron.txt. Could then expand it to figure out if an item is PvE vs PvP(See Wendigo as an example that is in both PvE and PvP files)
