### ISSUE TITLE
Choosy Voltron, but PVP and PVE seperated

### ISSUE THREAD

**Issue by Hillgrove** [48klocs/dim-wish-list-sources#130]
I don't PVP, and thus I'd love a PVE only wishlist.

Is this something that's possible?

Other than that I can only say thanks for making the game just that bit easier to understand and get into.

**Comment by bradleypriest** [comment]
Hey @Hillgrove, I'm completely unrelated to this project, but I'd been thinking about this a bit myself when I saw this issue.

I've scratched my own itch a bit here and built a quick automated script (checks every day at midnight) that pulls these wish lists and automatically filters out the PVE rolls to create new wishlists.

You can find it at https://github.com/bradleypriest/filtered_voltron, and the specific wishlist URL for DIM at https://raw.githubusercontent.com/bradleypriest/filtered_voltron/main/dist/choosy_voltron-pve.txt

I think it works ok, but I haven't exactly been able to eyeball the massive lists to determine so.
Feel free to fork it/send a PR if you find an issue or need to tweak it slightly.

**Comment by 48klocs** [comment]
For any number of reasons, teasing out activity-specific lists is not a thing I'm interested in doing myself.

You can generally use `wishlistnotes` to find what you're after in a voltron.
