### ISSUE TITLE
Season 20 Iron Banner Weapons Not Matching Wishlist

### ISSUE THREAD

**Issue by dannyh** [48klocs/dim-wish-list-sources#135]
Season 20 Iron Banner weapons aren't matching the wishlist, previous weapons like:

Roar of the Bear
Gunnora's Axe
The Hero's Burden
etc.

**Comment by JpDeathBlade** [comment]
The main reason for this is that Bungie made them new weapons. So they do not share the hash of their previous version. You can test that in game by trying to infuse a new one into an old one, it will cost an Upgrade Module instead of Glimmer, because they are "different" items.

No idea why Bungie did that.

**Comment by 48klocs** [comment]
Sorry for taking a minute - work and travel.

Anyway, I'm not super sure how to handle this, as I'd kind of expect new weapons to have a new perk pool? If they're strictly overlapping, then I'm not against taking this away to build out a D2AI alias from prior weapon -> current weapon and expanding the logic DIM uses internally to carry those picks forwards.

The rub being that those were picks from a prior season, and the sandbox changes a lot.

**Comment by CryoRenegade** [comment]
So using the examples above, light.gg states that ROTB is still the same across both listings. However when we get to Gunnora's, they changed the mag perks removing accurized, tactcial, and steady whist adding light, ricochet, high-cal, and armor-piercing.
Afaik all guns sans ROTB and The Wizened Rebuke got a change in the mag perks (please correct me if I'm wrong) and should be reevaluated to see if a tiny tweak needs to be applied to the existing rolls or if we need new rolls.
The wizened rebuke def needs a review as it has a whole different perk pool in both column 3 and 4.

**Comment by 48klocs** [comment]
Different rolls, different season.
