### ISSUE TITLE
Typo in Roll Tags

### ISSUE THREAD

**Issue by 2Pillows** [48klocs/dim-wish-list-sources#154]
Hello,

In voltron.txt on line 52509 there is a typo of "backupe roll":

// Lingering Dread (PvE backupe roll)
// Smart Drift Control, Spike Grenades, Auto-Loading Holster, Vorpal Weapon
//notes:Inspired by DMB Player Versus Enemies Podcast 19. PvE backup roll for solo yellow bar burst damage. Bitterspite origin trait is excellent - faster reload is always useful. The first breech-loading Stasis Grenade Launcher is a great utility weapon. Smart Drift Control helps a bit with handling and velocity, and Spike Grenades boosts single target damage. Auto-Loading Holster lets you swap and continue damage with a primary while reloading and Vorpal Weapon adds a flat 15% damage boost. Recommended MW: Handling or Velocity, with a damage-boosting (Major, Boss or Taken Spec) mod.|tags:pve
dimwishlist:item=2026087437&perks=3300816228,1546637391

There are a couple of other instances of the same typo on lines 35788 and 35816.

**Comment by 48klocs** [comment]
Thanks, updated.
