### ISSUE TITLE
Maybe missing roll

### ISSUE THREAD

**Issue by 48klocs** [48klocs/dim-wish-list-sources#2]
Got a report over on Discord.

Waking Moment
Chambered + Extended + Slideways + Swashbuckler

From panda's spreadsheet (not sure which)

- [x] check to verify that the perk hashes are all correct.
- [x] check to verify that Waking Moment's item hash is correct (and that a second inventory item definition hasn't sprouted)

**Comment by golfinry** [comment]
Noticed similiar issue with my One Small Step. 

Here are the rolls I have: 
https://destinytracker.com/destiny-2/db/items/1016668089?perks=996573084,1482024992,106909392,1631667848,2679249093,3205869473,2788909693,384158423,0,2302094943

Should match the PVE Godroll :

One Small Step | Shotgun | Rapid-Fire Frame | 
Smallbore, Barrel Shroud, Corkscrew Rifling | 
Tactical Mag, Extended Mag, Appended Mag | 
Grave Robber, Quickdraw, Auto-Loading Holster | 
One-Two Punch, Rampage |

**Comment by 48klocs** [comment]
I made a mistake and included masterworks in the wish list files for panda's latest, and their presence was causing a whole bunch of rolls to be ignored.

If you get the latest `voltron.txt`, it should be working now.

**Comment by golfinry** [comment]
Confirmed working! Thank you for all the work you put into this and DIM. 

![image](https://user-images.githubusercontent.com/56240137/69104777-d1e01e00-0aac-11ea-8437-0d70ccc0dc1d.png)
