### ISSUE TITLE
Source list clean up

### ISSUE THREAD

**Issue by rngoode1** [48klocs/dim-wish-list-sources#22]
Ive been combing over the source lists and found two issues. 

1. One weapon entry will have the same set of rolls repeated up to 3-4 times. This may be isolated to the panda_shadowkeep sheets. The entry below should only be the first four lines but somehow it was duplicated. Its considerably worse on others, which feeds into the second thing i noticed.
```
// Exit Strategy
dimwishlist:item=4227181568&perks=839105230,1885400500,205890336,4082225868
dimwishlist:item=4227181568&perks=839105230,1885400500,4071163871,4082225868
dimwishlist:item=4227181568&perks=839105230,1885400500,205890336,3708227201
dimwishlist:item=4227181568&perks=839105230,1885400500,4071163871,3708227201
dimwishlist:item=4227181568&perks=839105230,1885400500,205890336,4082225868
dimwishlist:item=4227181568&perks=839105230,1885400500,4071163871,4082225868
dimwishlist:item=4227181568&perks=839105230,1885400500,205890336,3708227201
dimwishlist:item=4227181568&perks=839105230,1885400500,4071163871,3708227201
```

2. Some of these weapons will have two sets of rolls, pointing to different hash IDs. This was present on the majority of panda's sheets. One ID points to the actual usable item, while one is just a "dummy item" which has the listed description 

> "These items are not actually ones you can obtain in the game, but rather are used to display information."

I figure cleaning these lists up will only help future updates, whether its creating custom lists, adding more notes or splitting the lists to create customizable voltrons. I have already went though all of the panda lists and could finish the rest if it would help.

**Comment by 48klocs** [comment]
I didn't dig deep when it comes to weapons with multiple `InventoryItem` definitions (or perks defined multiple times) to figure out which can actually be instanced. That was an especially big headache with Season of Dawn, but there have been past culprits like that. I'm hesitant to remove those (unless I'm really pointing to collectibles).

Dupes like you found there are pretty straightforward cut 'n paste failures on my part, but loading de-dupes, so it's just a matter of a bit of file size (which would be nice to reclaim).

PRs are cool.

**Comment by 48klocs** [comment]
Clarifying what I'm interested in vs. not - the `Exit Strategy` type mistake, where I pasted the same block multiple times? I'd definitely be interested in removing those.

The duplicate hash, where they both point to `InventoryItem`s (even if one says it can't be displayed)? I am not interested in removing those, on the probably impossible off chance that the description is misleading.

**Comment by rngoode1** [comment]
Sorry for the delay, I will continue to work on them when I have time. 

The Exit Strategy example was mostly isolated to that one sheet so its not something thats common thankfully.

As far as Hash IDs go I confirm using Destiny Data Explorer. I try to clean these up as much as possible to keep it easier to manage, since I use them for more than just DIM.

So if you need or want ill probably have these more OCD voltrons forked.
