### ISSUE TITLE
Lack of existing notes in voltron file

### ISSUE THREAD

**Issue by Joldror** [48klocs/dim-wish-list-sources#31]
There's quite a lot of notes added (through script IIRC) to old individual rolls files but just realised there are no notes for this weapons in the voltron equivalent. I noticed a lack of notes in voltron but I thought those weapons didn't have notes in their original files. I just used the "panda_season_drifter_pve.txt" and "panda_season_drifter_pvp.txt" on dim to see what's what with my gnawing hungers and to my surprise there's notes in there.

So there's a problem transfering this to the voltron file?

**Comment by 48klocs** [comment]
I think those notes were added as part of a separate PR? I don't super remember.

I'd be fine with getting another PR to sort that out.
