### ISSUE TITLE
Question: Is there some sort of easy to use viewer?

### ISSUE THREAD

**Issue by sitch** [48klocs/dim-wish-list-sources#33]
I wasn't really able to find any way of viewing some UI for the wishlist.  Maybe there is some secret menu in DIM i don't know about?

But it would be nice to just take:
`wishlist.txt` -> render items in DIM
or even just
`wishlist.txt` -> `readable_wishlist.csv`

Thoughts?

**Comment by 48klocs** [comment]
The links to the original spreadsheets/breakdowns are not a secret.

**Comment by sitch** [comment]
@48klocs Please share if you can! I just end up going to a whole bunch of disparate reddit links from https://www.reddit.com/r/sharditkeepit/comments/dhihw1/so_you_think_you_have_a_god_roll/
