### ISSUE TITLE
How to generate my own voltron files

### ISSUE THREAD

**Issue by adamjford** [48klocs/dim-wish-list-sources#35]
Hi there,

I've been maintaining my own personal fork of the project so that I can add my own custom wishlist rolls to the voltron files. I've just been adding them directly to those files, but I'd like to keep things a little more organized and mantain my own "content creator" folder like you have them set up. I can certainly figure out how to add a new folder for the existing scripts to look at. However, I can't figure out for the life of me what code is actually used to compile the voltron files! Neither of the scripts set up in the package.json seem to do it, and there is no main index.js file (or its .ts counterpart) anywhere.

I'm new to node, so I apologize if I'm missing anything obvious. 😅

Thank you for compiling this resource and making it available to DIM!

**Comment by 48klocs** [comment]
The `voltron`s are (currently) generated by copy + paste.

It can take hours to make them, I haven't lost any sleep over it taking me seconds to paste at the end.

**Comment by adamjford** [comment]
Ah, that works. Thanks for the response! 🙂
