### ISSUE TITLE
Toil and trouble has full auto in last column

### ISSUE THREAD

**Issue by buncieboy343** [48klocs/dim-wish-list-sources#37]
There is a few lines for toil and trouble that have it roll with slideshot and full auto trigger system, despite the fact they both roll in the 3rd column. Couldn't work out exactly where the roll was sourced from, most recent list above it is "// from https://docs.google.com/spreadsheets/d/1D4Fu6fSoSrPhlSOmCn_n1bItSNGZHbZxNI6_lVpoeB8/edit#gid=0", but that last doesn't list toil and trouble.

Could be intended as a god roll because you can then switch between the two, but seems odd to specify 2 perks in the same column.

Rolls:
dimwishlist:item=2957367743&perks=1047830412,791862061,3161816588,2117683199
dimwishlist:item=2957367743&perks=1332244541,791862061,3161816588,2117683199
dimwishlist:item=2957367743&perks=1047830412,1087426260,3161816588,2117683199
dimwishlist:item=2957367743&perks=1332244541,1087426260,3161816588,2117683199
dimwishlist:item=2957367743&perks=1047830412,106909392,3161816588,2117683199
dimwishlist:item=2957367743&perks=1332244541,106909392,3161816588,2117683199
dimwishlist:item=2957367743&perks=1047830412,791862061,3300816228,2117683199
dimwishlist:item=2957367743&perks=1332244541,791862061,3300816228,2117683199
dimwishlist:item=2957367743&perks=1047830412,1087426260,3300816228,2117683199
dimwishlist:item=2957367743&perks=1332244541,1087426260,3300816228,2117683199
dimwishlist:item=2957367743&perks=1047830412,106909392,3300816228,2117683199
dimwishlist:item=2957367743&perks=1332244541,106909392,3300816228,2117683199

**Comment by 48klocs** [comment]
I take it this is in the voltrons?

I'm kind of... not all that pressed about a mistake in a forgettable shotgun. If you'd like to submit a PR, that'd be cool.

**Comment by buncieboy343** [comment]
Happy to submit a PR to remove the rolls, as I'm assuming this is a mistake (either source list or in copying over)? New to using Voltron so not sure if some rolls are supposed to be god rolls as you can switch between the two perks.

**Comment by 48klocs** [comment]
The voltrons are just compiled versions of the source files in the repo. Any change made should be made to the source file(s) as well as the collected big files.

**Comment by 48klocs** [comment]
Thanks for the PR!
