### ISSUE TITLE
masterworks in the wishlist file broken wishlist 

### ISSUE THREAD

**Issue by tanglueyi** [48klocs/dim-wish-list-sources#4]
Hi developer, first of all, my Eglish is bad, so I'll try my best to tell you how masterwork in the wishlist file is broken.

I got a One Small Step last week, and the roll is:
**Smallbore / Extended Mag / Quickdraw / One-Two Punch, Reload.**
This is a godroll right? But DIM didn't show me as a godroll, fortunately, I've read panda's Reddit post I know this is a godroll so I didn't shard it.
When I fully masterworked it, the symbol appears.↓
![CleanShot 2019-11-18 at 16 09 19@2x](https://user-images.githubusercontent.com/3315564/69035148-e3c6b000-0a1d-11ea-8515-d9fc7c64bd76.png)

What a big problem! If I haven't read that post, I may have already shard this. I tested my ANCIENT GOSPEL **(Fluted Barrel / Extended Mag / Rapid Hit / Swashbuckler, Range - t2)** use `dimwishlist:item=48643186&perks=1840239774,2420895100,247725512,4082225868,684616255`
the same thing happened, no symbol. ↓
![CleanShot 2019-11-18 at 16 24 41@2x](https://user-images.githubusercontent.com/3315564/69036054-ff32ba80-0a1f-11ea-833a-b46ebd15d48f.png)
Hope you understand what I say, Imagine how many people will shard the weapon that should have been retained. Please fix this.

Edit: [Panda's godroll spreadsheets](https://docs.google.com/spreadsheets/d/1UlPqO4koKRcqMxl2VO4JzdgkKyY7LW07W0k91S_Yl8U/edit#gid=306657165)

**Comment by 48klocs** [comment]
Thanks for pointing this out to me - I made a mistake in translating a couple of panda's lists, and thought that masterworks were intentionally skipped by code (they're not).

I removed masterwork hashes from the sources + voltron. If you grab an updated version, it should be working now.
