### ISSUE TITLE
List Files have differing formats

### ISSUE THREAD

**Issue by bivalent** [48klocs/dim-wish-list-sources#76]
https://github.com/bivalent/DIM-to-LL-converter/issues/1#issue-1118108475
For reference, this is a link to an issue describing the mismatching files that I'm forwarding to this repository to review.

--

There seems to be a mismatch between various files of this repository. For example, the front-facing files (voltrons) and the list generation tool both seem to use the same format. Links to them:

https://raw.githubusercontent.com/48klocs/dim-wish-list-sources/master/choosy_voltron.txt

and the provided list generation tool:
https://48klocs.github.io/wish-list-magic-wand/fingerwave.html

However, those are both different than the files found here: 
https://github.com/48klocs/dim-wish-list-sources/blob/master/AyyItsChevy/super_pog_s14.txt

Is there a tool or system in place that can adjust the formatting so they're all the same? I'd like to have my script (DIM format to Little Light format) work across all the files in this repository for folks looking to upload and adjust what they find here.

**Comment by 48klocs** [comment]
Little Light's Wishlist Manager tool already provides a bridge to/from the flat text format DIM uses to the JSON format they use. We've been internally discussing moving towards a more JSON-y format as well.

Fingerwave spit out JSON at one point, but that was never valid anywhere.

As it stands, this question is fairly vague. If you find issues or have something more concrete, please feel free to open a new one.

**Comment by bivalent** [comment]
Hey, thanks for replying. A bit confused on a few things you brought up:

> already provides a bridge to/from the flat text format DIM uses

Actually.... they dont. 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/3164760/152919826-572665ec-5cf2-49ae-a115-f6e81d3dc9fc.png">
Notice the option is disabled. Unless I'm missing something on my end.

> As it stands, this question is fairly vague.

I'm sorry it was vague, I'll try rewording. As a contributor / community member, I'd like to be able to write scripts that work across the repository, on all wishlist files, as to optimize contributions and overall just make lives easier. I have a script that would do this conversion from DIM to LL json, however since the files in the DIM repository are _not_ standardized, the script does not work across the whole repository. This makes it difficult for people looking to import specific files to LL, and are unable to because there's no import functionality like what I created.

My question was: Is there a way that you know of to fix the formatting on that file & others, so that my script can function like it currently does on the voltron files? It would be beneficial to have a single file format across the whole repository. A contributor noticed this inconsistant formatting and brought it up on my open source script I wrote and used for a previous PR here.

**Comment by 48klocs** [comment]
@bivalent ah - I thought that that Little Light's tool read in URL-y wish lists as well as JSON-y ones.

To the best of my knowledge, DIM understands all of the wish list lines in the files here, so I'd take a look at its logic and pattern after that - it's a some regexes, a few data structures, and a bit of tracking logic from what I remember of what I wrote.

If you find flaws in files, concrete examples are welcomed. That said, inconsistent formatting isn't a flaw - the files were built across time and DIM supports some optional variations/"versions" of the line formats.

**Comment by bivalent** [comment]
Thanks, will take a look for that regex. Appreciate your review and the project as a whole, it's done wonders for the community. Cheers!
