### ISSUE TITLE
trashlist - wrong comment and weapon type - ACANTHA-D XK8434

### ISSUE THREAD

**Issue by mike-seven** [48klocs/dim-wish-list-sources#8]
Grenade launcher treated as SMG with SMG comments.

https://github.com/48klocs/dim-wish-list-sources/blob/6ca8a4395896e9d6abf72cf6ee42f189f675f21d/trash_rolls.txt#L20

**Comment by 48klocs** [comment]
Someone on reddit (was that you?) mentioned this, and I updated it to Atalanta-D. Thanks for spotting it and letting me know!
