### ISSUE TITLE
trashlist - granade launchers with spikes/volatile launch/fieldprep/quickdraw are rather demanded

### ISSUE THREAD

**Issue by mike-seven** [48klocs/dim-wish-list-sources#9]
From a relatively new player perspective, it is not easy to find a good granade launcher. I was surprised Edge Transit with mentioned perks is marked as trash. It is worst than Wendigo, also than some 150 rpms, but not trashy. Please adjust, especially for new players, old ones will manage this.

**Comment by 48klocs** [comment]
This sort of demonstrates the limits of wish lists - I don't really know much about rolls myself, but it doesn't take a spreadsheet+crucible wizard to figure out who the community trusts, so I use their recommendations.

Which is generally useful, but they're made at points in time, and sandbox rebalances can happen (many were made before spike grenades became the DPS no-brainer choice), and recommended perks don't change.

If you can point me to a primary source that says "this/these combinations of perks makes any grenade launcher a must have", then I'll happily add it to voltron.
